const data = {
    product:[
        {
            _id: "1",
            name:'Nike slime shirt',
            category: 'shirts',
            image:'images/image-1.jpg',
            price:120,
            brand:'nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quatity product',
        },
        {
            _id: "2",
            name:'adidas fit shirts shirt',
            category: 'shirts',
            image:'images/image-2.jpg',
            price:100,
            brand:'adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quatity product',
        },    {
            _id: "3",
            name:'lacoste free shirt',
            category: 'shirts',
            image:'images/image-3.jpg',
            price:220,
            brand:'lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'high quatity product',
        },    {
            _id: "4",
            name:'Nike slime pant',
            category: 'pant',
            image:'images/image-4.jpg',
            price:78,
            brand:'nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quatity product',
        },    {
            _id :"5",
            name:'puma slime pant',
            category: 'pant',
            image:'images/image-5.jpg',
            price:65,
            brand:'puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quatity product',
        },    {
            _id :"6",
            name:'adidas fit pant',
            category: 'pant',
            image:'images/image-6.jpg',
            price:139,
            brand:'adidas',
            rating: 4.5,
            numReviews: 15,
            description: 'high quatity product',
        },
    ],
}
export default data;
